## Les thématiques scientifiques et leurs enjeux

L'unité de recherche est invitée à présenter les thématiques de recherche qu'elle a abordées au cours de la période de référence, en les situant dans le contexte international et \textbf{en s'appuyant sur les faits marquants qu'elle considère comme des avancées scientifiques remarquables}. Ces faits scientifiques marquants seront également détaillés dans la réponse à la référence 1 du domaine 3 du référentiel de l'autoévaluation. Ils répondent à des enjeux scientifiques, technologiques, culturels, économiques ou sociétaux. Le cas échéant, cet exposé des thématiques scientifiques pourra prendre en compte la structuration de l'unité de recherche en équipes qui pourront présenter leurs propres thématiques. Ce texte pourra être substantiel tout en restant d'une longueur raisonnable et adapté à la taille de l'unité de recherche. Il trouvera un écho dans le profil d'activités défini dans le paragraphe 4 de ce chapitre ainsi que dans le portfolio, objet du deuxième chapitre de ce document d'autoévaluation. Les éléments principaux de ce paragraphe seront brièvement repris, au titre de contexte, dans le dernier chapitre consacré à la trajectoire de l'unité de recherche. 

