### Domaine 2. Les résultats, le rayonnement et l'attractivité scientifiques de l'unité

Ce domaine se décline en quatre références qui portent essentiellement sur les réalisations scientifiques de l’unité et leur traduction dans une production scientifique qui ne sacrifie pas la qualité à la quantité.

#### Référence 1. L’unité est reconnue pour ses réalisations scientifiques qui satisfont à des critères de qualité {.unnumbered}

L’unité de recherche est invitée à présenter les thématiques de recherche qu’elle a abordées au cours de la période de référence, en les situant dans le contexte international. L’unité analyse ses réalisations scientifiques. Elle s’appuie en particulier sur le portfolio pour montrer en quoi celles-ci reposent sur des fondements théoriques et méthodologiques solides, qu’elles sont originales, qu’elles présentent un apport à la connaissance, qu’elles traduisent un positionnement national et international de ses recherches et qu’elles répondent à des enjeux scientifiques, technologiques, culturels, économiques ou sociétaux.

L’unité de recherche s’appuiera sur les faits marquants qu’elle considère comme des avancées scientifiques remarquables. Ces faits scientifiques marquants (découvertes, inventions, avancées méthodologiques, nouveaux concepts, ruptures, etc.) seront détaillés et ils pourront faire l’objet d’un développement substantiel.

L’unité décrit sa politique en matière de réponse à des appels à projets aussi bien internationaux que nationaux et locaux. Elle en présente les résultats.

L’unité expose son implication, à différents niveaux, dans des dispositifs et des projets financés par les programmes d’investissements nationaux (PIA, CPER, par exemple), et les bénéfices qu’elle en retire.

L’unité illustre le rayonnement de ses travaux par des indices de reconnaissance : membres d’institutions, lauréats de prix, distinctions, etc.


#### Référence 2. Les activités de recherche de l’unité donnent lieu à une production scientifique de qualité {.unnumbered}

L’unité montre qu’elle ne sacrifie pas la qualité à la quantité et présente sa stratégie de diffusion des connaissances. Elle analyse la qualité et la diversité des supports et des conférences choisis pour la diffusion de ses résultats.

Elle mentionne les dispositifs mis en œuvre pour accompagner les personnels chercheurs débutants dans leur activité de diffusion des connaissances.

Elle analyse les éventuels déséquilibres de production entre ses différentes équipes et elle décrit les moyens mis en place pour accompagner les personnels les moins actifs en la matière.

Elle souligne l’apport des personnels d’appui à la recherche.

#### Référence 3. L’unité participe à l’animation et au pilotage de sa communauté {.unnumbered}

L’unité précise les manifestations scientifiques qu’elle a organisées et précise son implication.

Elle indique si elle exerce des responsabilités éditoriales dans des revues ou des collections d’ouvrages reconnues internationalement.

L’unité montre comment elle s’implique dans des réseaux, des instances de pilotage de la recherche ou d’expertise scientifique à l’échelle internationale, européenne ou nationale.

L’unité décrit sa politique d’invitation des personnalités scientifiques.


#### Référence 4. La production scientifique de l’unité respecte les principes de l’intégrité scientifique, de l’éthique et de la science ouverte. Elle est conforme aux directives applicables dans ce domaine {.unnumbered}

L’unité précise les moyens mis en œuvre pour garantir la traçabilité et, le cas échéant, la reproductibilité de ses résultats (carnets de laboratoires, logiciels anti-plagiat, procédures internes d’examen – dont de relecture – par les pairs, procédures d’archivage des données et des codes sources, etc.).

L’unité décrit la mise en œuvre de la stratégie de ses tutelles en matière d’intégrité scientifique et de science ouverte.

Elle décrit les moyens par lesquels elle accompagne ses personnels dans le choix de supports appropriés de diffusion (pour éviter, par exemple, les conférences et revues dites « prédatrices ») et pour une juste prise en compte des contributions (en particulier dans les co-signatures).

L’unité indique les dispositions mises en place pour que sa production scientifique soit le résultat de recherches respectant la personne humaine, la vie animale.

L’unité définit sa politique en matière de science ouverte.
