## Trajectoire d'unité et projet commun

La trajectoire est entendue selon deux dimensions : la dynamique et l'ambition de recherche, d'une part, l'organisation et la vie du laboratoire, d'autre part. Elle est décrite à l'échelle de l'unité et peut être ensuite déclinée à celle des équipes.
L'unité est invitée à décrire, de façon très synthétique, son historique scientifique de long terme et à rappeler les objectifs qu'elle s'était assignés lors de la précédente évaluation, la stratégie qu'elle avait mise en place, et les défis qu'elle comptait relever. Ces éléments de caractérisation scientifique permettent d'opérer une analyse critique, de confronter les réalisations aux objectifs initiaux, de discuter des réussites et des échecs. L'unité souligne les réorientations qu'elle a mises en œuvre. 

L'unité précise comment elle s'inscrit aujourd'hui dans les champs de ses diverses interventions (scientifique, expertise, valorisation, formation, dissémination, etc.), aux niveaux national et international, en s'appuyant sur une analyse de l'état de l'art.

L'unité décrit sa projection scientifique sur la base de son autoévaluation, de ses acquis de recherche et des nouveaux enjeux de recherche identifiés. En se plaçant dans la perspective de son projet scientifique à cinq ans, l'unité présente sa vision prospective de l'évolution de son domaine scientifique, sa contribution aux questionnements en cours et le positionnement du projet dans le champ scientifique national ou international. Elle indique ses points d'appui, les points à améliorer et les possibilités offertes par son environnement. Elle précise les risques liés à cet environnement. Elle présente comment elle soutient l'émergence de nouvelles thématiques, les sujets de recherche à risque ou les disciplines rares.

L'unité expose, dans une vision prospective, sa stratégie partenariale avec le monde académique (aux échelles locale, nationale, européenne et internationale) et le monde socio-économique et culturel. L'unité est également invitée à montrer comment son projet s'intègre dans la stratégie des établissements tutelles et dans la stratégie du site universitaire.

L'unité justifie la mise en cohérence de sa stratégie de recherche avec ses moyens et son organisation : comment son organisation et ses évolutions ont servi ses objectifs scientifiques et comment sa future organisation et ses demandes de moyens répondront à ses ambitions. L'unité précise, dans ce paragraphe, les effectifs, les moyens à mobiliser et le mode de structuration (organisation,  positionnement  et contribution des équipes, synergies entre les équipes, plateformes) pour accompagner ses orientations, ses objectifs scientifiques et ses choix stratégiques. Elle présente un plan d'actions portant sur les nouveaux enjeux des laboratoires : science et société, science ouverte, impact environnemental des activités de l'unité, parité de genre, intégrité scientifique par exemple. 

