---
title: "Modèle Quarto de document d'autoévaluation HCERES"
date: last-modified
lang: fr
author: UMR Machine
bibliography: [references-HAL.bib] # plusieurs fichiers possible
preface: |
  | Ce document constitue le rapport d'autoévaluation de l'unité XXX, élaboré dans le cadre de la campagne d'évaluation 2025-2026 de la vague A de l'HCERES.
  |
  | Il est accompagné du dépôt git \url{xxx} permettant de reproduire l'intégralité des analyses et sa compilation, à l'aide des extractions des bases RH et HAL de notre unité (en date du XX 2024).
  |
  | Lors de la lecture de ce document, notez que le PDF est navigable. Les liens en rouge et les références bibliographiques pointent sur des pages web ou sur les éléments correspondants de la bibliographie. De plus, les références bibliographiques sont données par type, avec une numérotation propre et une lettre pour préfixe facilitant le repérage (A - article de journal, C - acte de conférence, B - livre, I - chapitre d'ouvrage, T - mémoire de thèse de doctorat ou d'habilitation, S - logiciel et U - prépublication).
  |
  | Enfin, nous avons tenté d'adopter quelques règles d'écriture épicène -- ou non genrée --, comme l'utilisation de termes neutres, d'accord de proximité, ou l'énumération alternant féminin et masculin (par exemple, "des chercheuses et des enseignants-chercheurs"). Parfois, nous avons  accordé avec le genre des personnes concernées. Merci de l'indulgence du comité sur ce point.
format:
  hceres-pdf: default
---

<!-- Données, entête et packages additionnels -->
{{< include 0_entete_data.qmd >}}

# Informations générales pour le contrat en cours

<!-- Identité de l'UMR --> 
{{< include 1-1_identite_UMR.qmd >}}

<!-- Présentation de l'unité --> 
{{< include 1-2_presentation.qmd >}}

<!-- Environnement de recherche -->
{{< include 1-3_environnement.qmd >}}

<!-- Recommandations -->
{{< include 1-4_recommandations.qmd >}}

# Introduction du portfolio

<!-- PORTFOLIO: introduction --> 
{{< include 2_introduction_portfolio.qmd >}}

# Autoévaluation du bilan

Selon les domaines d'évaluation, l'unité appuie son argumentation sur :

- les données fournies dans le tableur « Données de caractérisation et de production » ;
- les éléments sélectionnés pour la constitution du portfolio ;
- des données fournies en annexe, le cas échéant.

Lorsqu’une référence ou un item ne sont pas pertinents pour l’unité, celle-ci n’est pas tenue de les aborder. Elle est encouragée à expliquer succinctement en quoi cela ne la concerne pas.

La réponse aux différentes références n’appelle pas un développement d’ampleur identique. L’unité s’attachera à développer de manière plus substantielle les parties scientifiques et les références auxquelles elle porte un intérêt particulier.

Certaines références relèvent principalement de la politique des tutelles, il est important que l’unité décrive comment elle s’approprie cette politique, comment elle la met en œuvre ou comment elle sensibilise ses personnels sur ces sujets.


Pour les unités pluri-équipes : on commence par décliner les trois domaines à l'échelle de l'unité puis, pour chacune des équipes, on choisit parmi les domaines les références jugées pertinentes pour l'équipe.


## Autoévaluation de l'unité

<!-- Domaine 1 - Objectifs scientifiques, organisation et ressources de l'unité -->

{{< include 3_autoevaluation_unite_domaine_1.qmd >}}

<!-- Domaine 2 - Les résultats, le rayonnement et l'attractivité scientifiques de l'unité -->
{{< include 3_autoevaluation_unite_domaine_2.qmd >}}

<!-- Domaine 3 - Inscription des activités de recherche dans la société -->

{{< include 3_autoevaluation_unite_domaine_3.qmd >}}

{{< pagebreak >}}

## Autoévaluation des équipes (dans le cas des unités pluri-équipes)

Pour chacune des équipes, on choisit parmi les domaines les références jugées pertinentes pour l'équipe.

Dans l'éventualité où toutes les références devraient être abordées, on veille à respecter l'ordre de présentation.

## Synthèse de l'autoévaluation

L’unité et ses équipes, le cas échéant, évaluent leurs forces et faiblesses au regard des références des trois domaines d’évaluation.

# Trajectoire de l'unité

<!-- Trajectoire Unité --> 
{{< include 4_trajectoire_unite.qmd >}}

{{< pagebreak >}}

# Annexes {.appendix}

## Organigramme d'unité {.unnumbered}

